### PR TITLE
Add syntax highlighting #2

### PR DESCRIPTION
**Pull request by d1y**
image

### CODE REVIEW

**Review by caius — APPROVED** [review]
Awesome, thanks for the contribution!

**Comment by d1y** [comment]
Now submit the updated version to zed-extensions 🥳

**Comment by caius** [comment]
What version of Zed were you testing it on? I'm not seeing the extension show up at all on Zed Preview now - looks like they've changed how extensions work and there's more work to be done.

**Comment by d1y** [comment]
The zed-preview there is a button to test

image

Or a more hard-core test

```bash
cd ~/Library/Application\ Support/Zed/extensions/installed/make/languages/make/
rm -rf *

wget https://github.com/caius/zed-make/raw/main/languages/make/config.toml
wget https://github.com/caius/zed-make/raw/main/languages/make/highlights.scm
wget https://github.com/caius/zed-make/raw/main/languages/make/injections.scm
wget https://github.com/caius/zed-make/raw/main/languages/make/indents.scm
```

**Comment by caius** [comment]
I think I'd gotten it confused, neither reload nor uninstall worked and removing it from the installed dir didn't make it vanish after restarting Zed Preview either.

Eventually tricked it into functioning again 😅

**Comment by caius** [comment]
Raised upstream at https://github.com/zed-industries/extensions/pull/405

**Pull request merged**
